import { describe, it, expect } from 'vitest';
import { classifyCommit, createBatchGroups, estimateLlmCalls } from '../src/pipeline/batch.js';
import type { CommitDiff } from '../src/types/git.js';
import type { AnalysisConfig } from '../src/types/config.js';

const defaultAnalysisConfig: AnalysisConfig = {
  maxConcurrency: 3,
  smallCommitThreshold: 10,
  largeCommitThreshold: 500,
  skipMergeCommits: true,
  skipLockFiles: true,
  skipAutoGenerated: true,
};

function makeDiff(overrides: Partial<CommitDiff> = {}): CommitDiff {
  return {
    commit: {
      hash: 'abc123def456',
      abbreviatedHash: 'abc123d',
      author: { name: 'Test', email: 'test@test.com' },
      date: new Date(),
      message: 'test commit',
      subject: 'test commit',
      body: '',
      refs: '',
      parentHashes: ['parent1'],
      isMergeCommit: false,
    },
    files: [{ path: 'src/index.ts', status: 'modified' as const, additions: 50, deletions: 20, content: '+test', isBinary: false }],
    stats: {
      totalFiles: 1,
      totalAdditions: 50,
      totalDeletions: 20,
      effectiveChanges: 70,
    },
    ...overrides,
  };
}

describe('classifyCommit', () => {
  it('should classify merge commit as skipped', () => {
    const diff = makeDiff({
      commit: {
        ...makeDiff().commit,
        isMergeCommit: true,
        parentHashes: ['p1', 'p2'],
      },
    });
    expect(classifyCommit(diff, defaultAnalysisConfig)).toBe('skipped');
  });

  it('should classify small commit', () => {
    const diff = makeDiff({ stats: { totalFiles: 1, totalAdditions: 3, totalDeletions: 2, effectiveChanges: 5 } });
    expect(classifyCommit(diff, defaultAnalysisConfig)).toBe('small');
  });

  it('should classify large commit', () => {
    const diff = makeDiff({ stats: { totalFiles: 20, totalAdditions: 400, totalDeletions: 200, effectiveChanges: 600 } });
    expect(classifyCommit(diff, defaultAnalysisConfig)).toBe('large');
  });

  it('should classify normal commit', () => {
    const diff = makeDiff({ stats: { totalFiles: 3, totalAdditions: 50, totalDeletions: 20, effectiveChanges: 70 } });
    expect(classifyCommit(diff, defaultAnalysisConfig)).toBe('normal');
  });

  it('should classify mechanical commit by message pattern', () => {
    const diff = makeDiff({
      commit: { ...makeDiff().commit, message: 'Merge branch feature into main' },
    });
    expect(classifyCommit(diff, defaultAnalysisConfig)).toBe('mechanical');
  });
});

describe('createBatchGroups', () => {
  it('should batch small commits together', () => {
    const diffs = Array.from({ length: 6 }, () =>
      makeDiff({ stats: { totalFiles: 1, totalAdditions: 2, totalDeletions: 1, effectiveChanges: 3 } }),
    );
    const groups = createBatchGroups(diffs, defaultAnalysisConfig);
    const batchGroups = groups.filter((g) => g.type === 'batch');
    expect(batchGroups.length).toBeGreaterThan(0);
    expect(batchGroups[0]!.diffs.length).toBe(5);
  });

  it('should keep normal commits as single', () => {
    const diffs = [makeDiff()];
    const groups = createBatchGroups(diffs, defaultAnalysisConfig);
    expect(groups).toHaveLength(1);
    expect(groups[0]!.type).toBe('single');
  });
});

describe('estimateLlmCalls', () => {
  it('should not count skipped groups', () => {
    const groups = [
      { type: 'single' as const, diffs: [makeDiff()], classification: 'skipped' as const },
      { type: 'single' as const, diffs: [makeDiff()], classification: 'normal' as const },
    ];
    expect(estimateLlmCalls(groups)).toBe(1);
  });
});
