import type { GitPulseConfig } from '../types/config.js';

export const DEFAULT_CONFIG: GitPulseConfig = {
  provider: 'openai',
  model: 'gpt-4o',

  scoring: {
    weights: {
      codeQuality: 0.3,
      complexityImpact: 0.25,
      commitDiscipline: 0.25,
      collaboration: 0.2,
    },
    timeDecay: false,
    timeDecayLambda: 0.01,
    maxTokensPerDiff: 8000,
  },

  analysis: {
    maxConcurrency: 3,
    smallCommitThreshold: 10,
    largeCommitThreshold: 500,
    skipMergeCommits: true,
    skipLockFiles: true,
    skipAutoGenerated: true,
  },

  output: {
    format: 'terminal',
    anonymize: false,
  },

  privacy: {
    excludeFileContents: false,
    anonymize: false,
  },
};
