import { z } from 'zod';

export const dimensionWeightSchema = z.object({
  codeQuality: z.number().min(0).max(1).default(0.3),
  complexityImpact: z.number().min(0).max(1).default(0.25),
  commitDiscipline: z.number().min(0).max(1).default(0.25),
  collaboration: z.number().min(0).max(1).default(0.2),
});

export const scoringConfigSchema = z.object({
  weights: dimensionWeightSchema.default({}),
  timeDecay: z.boolean().default(false),
  timeDecayLambda: z.number().min(0).default(0.01),
  maxTokensPerDiff: z.number().int().positive().default(8000),
});

export const analysisConfigSchema = z.object({
  maxConcurrency: z.number().int().min(1).max(20).default(3),
  smallCommitThreshold: z.number().int().positive().default(10),
  largeCommitThreshold: z.number().int().positive().default(500),
  skipMergeCommits: z.boolean().default(true),
  skipLockFiles: z.boolean().default(true),
  skipAutoGenerated: z.boolean().default(true),
});

export const outputConfigSchema = z.object({
  format: z.enum(['terminal', 'json', 'markdown', 'html']).default('terminal'),
  outputPath: z.string().optional(),
  anonymize: z.boolean().default(false),
});

export const privacyConfigSchema = z.object({
  excludeFileContents: z.boolean().default(false),
  anonymize: z.boolean().default(false),
  anonymizeSalt: z.string().optional(),
});

export const llmProviderSchema = z.enum(['openai', 'anthropic', 'google', 'vertex', 'custom']);

export const gitPulseConfigSchema = z.object({
  provider: llmProviderSchema.default('openai'),
  model: z.string().default('gpt-4o'),
  apiKey: z.string().optional(),
  baseURL: z.string().url().optional(),

  scoring: scoringConfigSchema.default({}),
  analysis: analysisConfigSchema.default({}),
  output: outputConfigSchema.default({}),
  privacy: privacyConfigSchema.default({}),
});

export type GitPulseConfigInput = z.input<typeof gitPulseConfigSchema>;
export type GitPulseConfigResolved = z.output<typeof gitPulseConfigSchema>;
