import type { DimensionWeight } from './scoring.js';

export type LLMProviderType = 'openai' | 'anthropic' | 'google' | 'vertex' | 'custom';

export interface GitPulseConfig {
  provider: LLMProviderType;
  model: string;
  apiKey?: string;
  baseURL?: string;

  scoring: ScoringConfig;
  analysis: AnalysisConfig;
  output: OutputConfig;
  privacy: PrivacyConfig;
}

export interface ScoringConfig {
  weights: DimensionWeight;
  timeDecay: boolean;
  timeDecayLambda: number;
  maxTokensPerDiff: number;
}

export interface AnalysisConfig {
  maxConcurrency: number;
  smallCommitThreshold: number;
  largeCommitThreshold: number;
  skipMergeCommits: boolean;
  skipLockFiles: boolean;
  skipAutoGenerated: boolean;
}

export interface OutputConfig {
  format: 'terminal' | 'json' | 'markdown' | 'html';
  outputPath?: string;
  anonymize: boolean;
}

export interface PrivacyConfig {
  excludeFileContents: boolean;
  anonymize: boolean;
  anonymizeSalt?: string;
}
