import * as fs from 'node:fs';
import * as path from 'node:path';
import { select, input, confirm } from '@inquirer/prompts';
import { theme } from '../ui/theme.js';
import type { LLMProviderType } from '@gitpulse/core';

export interface SetupResult {
  provider: LLMProviderType;
  model: string;
  apiKey?: string;
  baseURL?: string;
}

export async function runSetupWizard(targetDir: string): Promise<void> {
  console.log(theme.heading('\nGitPulse Configuration Wizard\n'));

  const provider = (await select({
    message: 'Select your LLM provider:',
    choices: [
      { value: 'openai', name: 'OpenAI (GPT-4o, GPT-4o-mini)' },
      { value: 'anthropic', name: 'Anthropic (Claude)' },
      { value: 'google', name: 'Google (Gemini)' },
      { value: 'vertex', name: 'Google Vertex AI (Gemini via Vertex)' },
      { value: 'custom', name: 'Custom (OpenAI-compatible endpoint)' },
    ],
  })) as LLMProviderType;

  const defaultModels: Record<string, string> = {
    openai: 'gpt-4o',
    anthropic: 'claude-sonnet-4-20250514',
    google: 'gemini-1.5-pro',
    vertex: 'gemini-1.5-pro',
    custom: 'default',
  };

  const model = await input({
    message: 'Model name:',
    default: defaultModels[provider] ?? 'gpt-4o',
  });

  let baseURL: string | undefined;
  if (provider === 'custom') {
    baseURL = await input({
      message: 'Base URL for the API:',
      validate: (v) => {
        try {
          new URL(v);
          return true;
        } catch {
          return 'Please enter a valid URL';
        }
      },
    });
  }

  const envVarNames: Record<string, string> = {
    openai: 'OPENAI_API_KEY',
    anthropic: 'ANTHROPIC_API_KEY',
    google: 'GOOGLE_GENERATIVE_AI_API_KEY',
    vertex: 'GOOGLE_VERTEX_API_KEY',
    custom: 'API_KEY',
  };

  const envVar = envVarNames[provider] ?? 'API_KEY';
  console.log(
    theme.dim(
      `\nTip: Set your API key via the ${theme.info(envVar)} environment variable.\n`,
    ),
  );

  const customize = await confirm({
    message: 'Customize scoring weights?',
    default: false,
  });

  let weights = {
    codeQuality: 0.3,
    complexityImpact: 0.25,
    commitDiscipline: 0.25,
    collaboration: 0.2,
  };

  if (customize) {
    console.log(theme.dim('Enter weights (must sum to 1.0):'));
    const cq = await input({ message: 'Code Quality weight:', default: '0.30' });
    const ci = await input({ message: 'Complexity & Impact weight:', default: '0.25' });
    const cd = await input({ message: 'Commit Discipline weight:', default: '0.25' });
    const co = await input({ message: 'Collaboration weight:', default: '0.20' });
    weights = {
      codeQuality: parseFloat(cq),
      complexityImpact: parseFloat(ci),
      commitDiscipline: parseFloat(cd),
      collaboration: parseFloat(co),
    };
  }

  const config = buildConfigYaml(provider, model, baseURL, weights);
  const configPath = path.join(targetDir, '.gitpulse.yml');

  fs.writeFileSync(configPath, config, 'utf-8');
  console.log(theme.success(`\nConfiguration saved to ${configPath}`));
}

function buildConfigYaml(
  provider: string,
  model: string,
  baseURL: string | undefined,
  weights: Record<string, number>,
): string {
  let yaml = `# GitPulse Configuration
provider: ${provider}
model: ${model}
`;

  if (baseURL) {
    yaml += `baseURL: ${baseURL}\n`;
  }

  yaml += `
scoring:
  weights:
    codeQuality: ${weights.codeQuality}
    complexityImpact: ${weights.complexityImpact}
    commitDiscipline: ${weights.commitDiscipline}
    collaboration: ${weights.collaboration}
  timeDecay: false
  maxTokensPerDiff: 8000

analysis:
  maxConcurrency: 3
  skipMergeCommits: true
  skipLockFiles: true
  skipAutoGenerated: true

output:
  format: terminal
  anonymize: false

privacy:
  excludeFileContents: false
  anonymize: false
`;

  return yaml;
}
